### ISSUE TITLE
What is the coding scene like in Spain?

### ISSUE THREAD

**Issue by CarlMungazi** [AdrianArroyoCalle/ama#10]

**Comment by AdrianArroyoCalle** [comment]
Although I'm still a student, I can tell you a few things

- Bad salaries and work conditions. This not only applies to programmers and designers but also to every job in Spain. Jobs have bad conditions due to crisis (scientific and engineering jobs). Most people think about moving to Germany or UK.

- Heavy influence of Microsoft technologies. Most programmers use Microsoft tools, because Microsoft was a company that translated their manuals into Spanish. Now, people speak a lot more of English, but legacy code is still there.

- Despite that, it's a very creative and inclusive community, with great ideas and always ready to help anybody.
