### ISSUE TITLE
What do you think about Rust?

### ISSUE THREAD

**Issue by sindresorhus** [AdrianArroyoCalle/ama#2]

**Comment by AdrianArroyoCalle** [comment]
It's a big chance! C was so great that today we are still using it on a massive scale. C++ isn't a bad language in my opinion but it's to big to understand well. So people get frustrated. Rust is on the right way because it offers something more than C++, safety, without losing other advantages. If you look at another C++ replacement-intents you will see that they didn't offer something that can't be accomplished with C++.
